/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos do FSC
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId?: string;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 0 */
  weightInGrams: number;
  /** @minimum 0 */
  heightInCentimeters: number;
  /** @minimum 0 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats404 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200ItemGoal =
  (typeof ListWorkoutPlans200ItemGoal)[keyof typeof ListWorkoutPlans200ItemGoal];

export const ListWorkoutPlans200ItemGoal = {
  HYPERTROPHY: "HYPERTROPHY",
  WEIGHT_LOSS: "WEIGHT_LOSS",
  ENDURANCE: "ENDURANCE",
  STRENGTH: "STRENGTH",
  GENERAL_FITNESS: "GENERAL_FITNESS",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  goal?: ListWorkoutPlans200ItemGoal;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyGoal =
  (typeof CreateWorkoutPlanBodyGoal)[keyof typeof CreateWorkoutPlanBodyGoal];

export const CreateWorkoutPlanBodyGoal = {
  HYPERTROPHY: "HYPERTROPHY",
  WEIGHT_LOSS: "WEIGHT_LOSS",
  ENDURANCE: "ENDURANCE",
  STRENGTH: "STRENGTH",
  GENERAL_FITNESS: "GENERAL_FITNESS",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBodyMealsItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  time: string;
  description: string;
  /** @minimum 0 */
  calories: number;
  /** @minimum 0 */
  proteinInGrams: number;
  /** @minimum 0 */
  carbsInGrams: number;
  /** @minimum 0 */
  fatInGrams: number;
};

export type CreateWorkoutPlanBody = {
  goal?: CreateWorkoutPlanBodyGoal;
  /** @minimum 0 */
  dailyWaterGoalInMl: number;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
  meals: CreateWorkoutPlanBodyMealsItem[];
};

export type CreateWorkoutPlan201Goal =
  (typeof CreateWorkoutPlan201Goal)[keyof typeof CreateWorkoutPlan201Goal];

export const CreateWorkoutPlan201Goal = {
  HYPERTROPHY: "HYPERTROPHY",
  WEIGHT_LOSS: "WEIGHT_LOSS",
  ENDURANCE: "ENDURANCE",
  STRENGTH: "STRENGTH",
  GENERAL_FITNESS: "GENERAL_FITNESS",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201MealsItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  time: string;
  description: string;
  /** @minimum 0 */
  calories: number;
  /** @minimum 0 */
  proteinInGrams: number;
  /** @minimum 0 */
  carbsInGrams: number;
  /** @minimum 0 */
  fatInGrams: number;
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  goal?: CreateWorkoutPlan201Goal;
  /** @minimum 0 */
  dailyWaterGoalInMl: number;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
  meals: CreateWorkoutPlan201MealsItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200Goal =
  (typeof GetWorkoutPlan200Goal)[keyof typeof GetWorkoutPlan200Goal];

export const GetWorkoutPlan200Goal = {
  HYPERTROPHY: "HYPERTROPHY",
  WEIGHT_LOSS: "WEIGHT_LOSS",
  ENDURANCE: "ENDURANCE",
  STRENGTH: "STRENGTH",
  GENERAL_FITNESS: "GENERAL_FITNESS",
} as const;

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200MealsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  time: string;
  description: string;
  calories: number;
  proteinInGrams: number;
  carbsInGrams: number;
  fatInGrams: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  goal?: GetWorkoutPlan200Goal;
  dailyWaterGoalInMl?: number;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
  meals: GetWorkoutPlan200MealsItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type DeleteWorkoutPlan401 = {
  error: string;
  code: string;
};

export type DeleteWorkoutPlan404 = {
  error: string;
  code: string;
};

export type DeleteWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanDetails200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlanDetails200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlanDetails200WorkoutDaysItemWeekDay];

export const GetWorkoutPlanDetails200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlanDetails200WorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutPlanDetails200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetWorkoutPlanDetails200WorkoutDaysItemWeekDay;
  isRest: boolean;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: GetWorkoutPlanDetails200WorkoutDaysItemExercisesItem[];
};

export type GetWorkoutPlanDetails200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlanDetails200WorkoutDaysItem[];
};

export type GetWorkoutPlanDetails401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanDetails404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlanDetails500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
  loadInKg?: number;
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDay200WeekDay;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutDayBody = {
  /** @minLength 1 */
  name: string;
  isRest: boolean;
  /** @minimum 1 */
  estimatedDurationInSeconds: number;
};

export type UpdateWorkoutDay200WeekDay =
  (typeof UpdateWorkoutDay200WeekDay)[keyof typeof UpdateWorkoutDay200WeekDay];

export const UpdateWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type UpdateWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: UpdateWorkoutDay200WeekDay;
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
};

export type UpdateWorkoutDay401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutDay404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutDay500 = {
  error: string;
  code: string;
};

export type CreateWorkoutExerciseBody = {
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutExercise201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type CreateWorkoutExercise401 = {
  error: string;
  code: string;
};

export type CreateWorkoutExercise404 = {
  error: string;
  code: string;
};

export type CreateWorkoutExercise500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutExerciseBody = {
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type UpdateWorkoutExercise200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type UpdateWorkoutExercise401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutExercise404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutExercise500 = {
  error: string;
  code: string;
};

export type DeleteWorkoutExercise401 = {
  error: string;
  code: string;
};

export type DeleteWorkoutExercise404 = {
  error: string;
  code: string;
};

export type DeleteWorkoutExercise500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type CreateMealBody = {
  /** @minLength 1 */
  name: string;
  time: string;
  description: string;
  /** @minimum 0 */
  calories: number;
  /** @minimum 0 */
  proteinInGrams: number;
  /** @minimum 0 */
  carbsInGrams: number;
  /** @minimum 0 */
  fatInGrams: number;
};

export type CreateMeal201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  time: string;
  description: string;
  calories: number;
  proteinInGrams: number;
  carbsInGrams: number;
  fatInGrams: number;
};

export type CreateMeal401 = {
  error: string;
  code: string;
};

export type CreateMeal404 = {
  error: string;
  code: string;
};

export type CreateMeal500 = {
  error: string;
  code: string;
};

export type UpdateMealBody = {
  /** @minLength 1 */
  name: string;
  time: string;
  description: string;
  /** @minimum 0 */
  calories: number;
  /** @minimum 0 */
  proteinInGrams: number;
  /** @minimum 0 */
  carbsInGrams: number;
  /** @minimum 0 */
  fatInGrams: number;
};

export type UpdateMeal200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  order: number;
  name: string;
  time: string;
  description: string;
  calories: number;
  proteinInGrams: number;
  carbsInGrams: number;
  fatInGrams: number;
};

export type UpdateMeal401 = {
  error: string;
  code: string;
};

export type UpdateMeal404 = {
  error: string;
  code: string;
};

export type UpdateMeal500 = {
  error: string;
  code: string;
};

export type DeleteMeal401 = {
  error: string;
  code: string;
};

export type DeleteMeal404 = {
  error: string;
  code: string;
};

export type DeleteMeal500 = {
  error: string;
  code: string;
};

export type AnalyzeMealPhotoBody = {
  /** @minLength 1 */
  image: string;
};

export type AnalyzeMealPhoto200 = {
  name: string;
  description: string;
  /** @minimum 0 */
  calories: number;
  /** @minimum 0 */
  proteinInGrams: number;
  /** @minimum 0 */
  carbsInGrams: number;
  /** @minimum 0 */
  fatInGrams: number;
};

export type AnalyzeMealPhoto401 = {
  error: string;
  code: string;
};

export type AnalyzeMealPhoto500 = {
  error: string;
  code: string;
};

export type GetWorkoutSessions200ItemSessionsItemWeekDay =
  (typeof GetWorkoutSessions200ItemSessionsItemWeekDay)[keyof typeof GetWorkoutSessions200ItemSessionsItemWeekDay];

export const GetWorkoutSessions200ItemSessionsItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutSessions200ItemSessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: GetWorkoutSessions200ItemSessionsItemWeekDay;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string;
  durationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutSessions200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  workoutPlanName: string;
  isActive: boolean;
  completedWorkoutsCount: number;
  totalTimeInSeconds: number;
  sessions: GetWorkoutSessions200ItemSessionsItem[];
};

export type GetWorkoutSessions401 = {
  error: string;
  code: string;
};

export type GetWorkoutSessions500 = {
  error: string;
  code: string;
};

export type UpdateExerciseLoadBody = {
  /** @minimum 0 */
  loadInKg: number;
};

export type UpdateExerciseLoad200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  loadInKg: number;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  recordedAt: string;
};

export type UpdateExerciseLoad401 = {
  error: string;
  code: string;
};

export type UpdateExerciseLoad404 = {
  error: string;
  code: string;
};

export type UpdateExerciseLoad500 = {
  error: string;
  code: string;
};

export type GetExerciseLoadHistory200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  loadInKg: number;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  recordedAt: string;
};

export type GetExerciseLoadHistory401 = {
  error: string;
  code: string;
};

export type GetExerciseLoadHistory404 = {
  error: string;
  code: string;
};

export type GetExerciseLoadHistory500 = {
  error: string;
  code: string;
};

export type GetWaterIntakeTodayParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  date: string;
};

export type GetWaterIntakeToday200EntriesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  amountInMl: number;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  recordedAt: string;
};

export type GetWaterIntakeToday200 = {
  goalInMl?: number;
  totalInMl: number;
  entries: GetWaterIntakeToday200EntriesItem[];
};

export type GetWaterIntakeToday401 = {
  error: string;
  code: string;
};

export type GetWaterIntakeToday500 = {
  error: string;
  code: string;
};

export type CreateWaterIntakeEntryBody = {
  /** @minimum 1 */
  amountInMl: number;
};

export type CreateWaterIntakeEntry201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  amountInMl: number;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  recordedAt: string;
};

export type CreateWaterIntakeEntry401 = {
  error: string;
  code: string;
};

export type CreateWaterIntakeEntry500 = {
  error: string;
  code: string;
};

export type ListMuscleGroups200ItemExerciseTemplatesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
};

export type ListMuscleGroups200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  exerciseTemplates: ListMuscleGroups200ItemExerciseTemplatesItem[];
};

export type ListMuscleGroups401 = {
  error: string;
  code: string;
};

export type ListMuscleGroups500 = {
  error: string;
  code: string;
};

export type CreateMuscleGroupBody = {
  /** @minLength 1 */
  name: string;
};

export type CreateMuscleGroup201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
};

export type CreateMuscleGroup401 = {
  error: string;
  code: string;
};

export type CreateMuscleGroup409 = {
  error: string;
  code: string;
};

export type CreateMuscleGroup500 = {
  error: string;
  code: string;
};

export type UpdateMuscleGroupBody = {
  /** @minLength 1 */
  name: string;
};

export type UpdateMuscleGroup200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
};

export type UpdateMuscleGroup401 = {
  error: string;
  code: string;
};

export type UpdateMuscleGroup404 = {
  error: string;
  code: string;
};

export type UpdateMuscleGroup409 = {
  error: string;
  code: string;
};

export type UpdateMuscleGroup500 = {
  error: string;
  code: string;
};

export type DeleteMuscleGroup401 = {
  error: string;
  code: string;
};

export type DeleteMuscleGroup404 = {
  error: string;
  code: string;
};

export type DeleteMuscleGroup500 = {
  error: string;
  code: string;
};

export type CreateExerciseTemplateBody = {
  /** @minLength 1 */
  name: string;
};

export type CreateExerciseTemplate201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  muscleGroupId: string;
};

export type CreateExerciseTemplate401 = {
  error: string;
  code: string;
};

export type CreateExerciseTemplate404 = {
  error: string;
  code: string;
};

export type CreateExerciseTemplate409 = {
  error: string;
  code: string;
};

export type CreateExerciseTemplate500 = {
  error: string;
  code: string;
};

export type UpdateExerciseTemplateBody = {
  /** @minLength 1 */
  name: string;
};

export type UpdateExerciseTemplate200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  muscleGroupId: string;
};

export type UpdateExerciseTemplate401 = {
  error: string;
  code: string;
};

export type UpdateExerciseTemplate404 = {
  error: string;
  code: string;
};

export type UpdateExerciseTemplate409 = {
  error: string;
  code: string;
};

export type UpdateExerciseTemplate500 = {
  error: string;
  code: string;
};

export type DeleteExerciseTemplate401 = {
  error: string;
  code: string;
};

export type DeleteExerciseTemplate404 = {
  error: string;
  code: string;
};

export type DeleteExerciseTemplate500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string) => {
  return `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user train data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me/`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Upsert user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me/`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Get user workout stats
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse404 = {
  data: GetStats404;
  status: 404;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse404
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[];
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Delete a workout plan
 */
export type deleteWorkoutPlanResponse204 = {
  data: unknown;
  status: 204;
};

export type deleteWorkoutPlanResponse401 = {
  data: DeleteWorkoutPlan401;
  status: 401;
};

export type deleteWorkoutPlanResponse404 = {
  data: DeleteWorkoutPlan404;
  status: 404;
};

export type deleteWorkoutPlanResponse500 = {
  data: DeleteWorkoutPlan500;
  status: 500;
};

export type deleteWorkoutPlanResponseSuccess = deleteWorkoutPlanResponse204 & {
  headers: Headers;
};
export type deleteWorkoutPlanResponseError = (
  | deleteWorkoutPlanResponse401
  | deleteWorkoutPlanResponse404
  | deleteWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type deleteWorkoutPlanResponse =
  | deleteWorkoutPlanResponseSuccess
  | deleteWorkoutPlanResponseError;

export const getDeleteWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`;
};

export const deleteWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<deleteWorkoutPlanResponse> => {
  return customFetch<deleteWorkoutPlanResponse>(
    getDeleteWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get a workout plan with all days and exercises, for editing
 */
export type getWorkoutPlanDetailsResponse200 = {
  data: GetWorkoutPlanDetails200;
  status: 200;
};

export type getWorkoutPlanDetailsResponse401 = {
  data: GetWorkoutPlanDetails401;
  status: 401;
};

export type getWorkoutPlanDetailsResponse404 = {
  data: GetWorkoutPlanDetails404;
  status: 404;
};

export type getWorkoutPlanDetailsResponse500 = {
  data: GetWorkoutPlanDetails500;
  status: 500;
};

export type getWorkoutPlanDetailsResponseSuccess =
  getWorkoutPlanDetailsResponse200 & {
    headers: Headers;
  };
export type getWorkoutPlanDetailsResponseError = (
  | getWorkoutPlanDetailsResponse401
  | getWorkoutPlanDetailsResponse404
  | getWorkoutPlanDetailsResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanDetailsResponse =
  | getWorkoutPlanDetailsResponseSuccess
  | getWorkoutPlanDetailsResponseError;

export const getGetWorkoutPlanDetailsUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}/details`;
};

export const getWorkoutPlanDetails = async (
  workoutPlanId: string,
  options?: RequestInit,
): Promise<getWorkoutPlanDetailsResponse> => {
  return customFetch<getWorkoutPlanDetailsResponse>(
    getGetWorkoutPlanDetailsUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Update a workout day (name, duration, rest status)
 */
export type updateWorkoutDayResponse200 = {
  data: UpdateWorkoutDay200;
  status: 200;
};

export type updateWorkoutDayResponse401 = {
  data: UpdateWorkoutDay401;
  status: 401;
};

export type updateWorkoutDayResponse404 = {
  data: UpdateWorkoutDay404;
  status: 404;
};

export type updateWorkoutDayResponse500 = {
  data: UpdateWorkoutDay500;
  status: 500;
};

export type updateWorkoutDayResponseSuccess = updateWorkoutDayResponse200 & {
  headers: Headers;
};
export type updateWorkoutDayResponseError = (
  | updateWorkoutDayResponse401
  | updateWorkoutDayResponse404
  | updateWorkoutDayResponse500
) & {
  headers: Headers;
};

export type updateWorkoutDayResponse =
  | updateWorkoutDayResponseSuccess
  | updateWorkoutDayResponseError;

export const getUpdateWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`;
};

export const updateWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  updateWorkoutDayBody: UpdateWorkoutDayBody,
  options?: RequestInit,
): Promise<updateWorkoutDayResponse> => {
  return customFetch<updateWorkoutDayResponse>(
    getUpdateWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutDayBody),
    },
  );
};

/**
 * @summary Add an exercise to a workout day
 */
export type createWorkoutExerciseResponse201 = {
  data: CreateWorkoutExercise201;
  status: 201;
};

export type createWorkoutExerciseResponse401 = {
  data: CreateWorkoutExercise401;
  status: 401;
};

export type createWorkoutExerciseResponse404 = {
  data: CreateWorkoutExercise404;
  status: 404;
};

export type createWorkoutExerciseResponse500 = {
  data: CreateWorkoutExercise500;
  status: 500;
};

export type createWorkoutExerciseResponseSuccess =
  createWorkoutExerciseResponse201 & {
    headers: Headers;
  };
export type createWorkoutExerciseResponseError = (
  | createWorkoutExerciseResponse401
  | createWorkoutExerciseResponse404
  | createWorkoutExerciseResponse500
) & {
  headers: Headers;
};

export type createWorkoutExerciseResponse =
  | createWorkoutExerciseResponseSuccess
  | createWorkoutExerciseResponseError;

export const getCreateWorkoutExerciseUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/exercises`;
};

export const createWorkoutExercise = async (
  workoutPlanId: string,
  workoutDayId: string,
  createWorkoutExerciseBody: CreateWorkoutExerciseBody,
  options?: RequestInit,
): Promise<createWorkoutExerciseResponse> => {
  return customFetch<createWorkoutExerciseResponse>(
    getCreateWorkoutExerciseUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createWorkoutExerciseBody),
    },
  );
};

/**
 * @summary Update an exercise in a workout day
 */
export type updateWorkoutExerciseResponse200 = {
  data: UpdateWorkoutExercise200;
  status: 200;
};

export type updateWorkoutExerciseResponse401 = {
  data: UpdateWorkoutExercise401;
  status: 401;
};

export type updateWorkoutExerciseResponse404 = {
  data: UpdateWorkoutExercise404;
  status: 404;
};

export type updateWorkoutExerciseResponse500 = {
  data: UpdateWorkoutExercise500;
  status: 500;
};

export type updateWorkoutExerciseResponseSuccess =
  updateWorkoutExerciseResponse200 & {
    headers: Headers;
  };
export type updateWorkoutExerciseResponseError = (
  | updateWorkoutExerciseResponse401
  | updateWorkoutExerciseResponse404
  | updateWorkoutExerciseResponse500
) & {
  headers: Headers;
};

export type updateWorkoutExerciseResponse =
  | updateWorkoutExerciseResponseSuccess
  | updateWorkoutExerciseResponseError;

export const getUpdateWorkoutExerciseUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/exercises/${exerciseId}`;
};

export const updateWorkoutExercise = async (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
  updateWorkoutExerciseBody: UpdateWorkoutExerciseBody,
  options?: RequestInit,
): Promise<updateWorkoutExerciseResponse> => {
  return customFetch<updateWorkoutExerciseResponse>(
    getUpdateWorkoutExerciseUrl(workoutPlanId, workoutDayId, exerciseId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutExerciseBody),
    },
  );
};

/**
 * @summary Delete an exercise from a workout day
 */
export type deleteWorkoutExerciseResponse204 = {
  data: unknown;
  status: 204;
};

export type deleteWorkoutExerciseResponse401 = {
  data: DeleteWorkoutExercise401;
  status: 401;
};

export type deleteWorkoutExerciseResponse404 = {
  data: DeleteWorkoutExercise404;
  status: 404;
};

export type deleteWorkoutExerciseResponse500 = {
  data: DeleteWorkoutExercise500;
  status: 500;
};

export type deleteWorkoutExerciseResponseSuccess =
  deleteWorkoutExerciseResponse204 & {
    headers: Headers;
  };
export type deleteWorkoutExerciseResponseError = (
  | deleteWorkoutExerciseResponse401
  | deleteWorkoutExerciseResponse404
  | deleteWorkoutExerciseResponse500
) & {
  headers: Headers;
};

export type deleteWorkoutExerciseResponse =
  | deleteWorkoutExerciseResponseSuccess
  | deleteWorkoutExerciseResponseError;

export const getDeleteWorkoutExerciseUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/exercises/${exerciseId}`;
};

export const deleteWorkoutExercise = async (
  workoutPlanId: string,
  workoutDayId: string,
  exerciseId: string,
  options?: RequestInit,
): Promise<deleteWorkoutExerciseResponse> => {
  return customFetch<deleteWorkoutExerciseResponse>(
    getDeleteWorkoutExerciseUrl(workoutPlanId, workoutDayId, exerciseId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200;
  status: 200;
};

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401;
  status: 401;
};

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404;
  status: 404;
};

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500;
  status: 500;
};

export type updateWorkoutSessionResponseSuccess =
  updateWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type updateWorkoutSessionResponseError = (
  | updateWorkoutSessionResponse401
  | updateWorkoutSessionResponse404
  | updateWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse =
  | updateWorkoutSessionResponseSuccess
  | updateWorkoutSessionResponseError;

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<updateWorkoutSessionResponse>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Add a meal to a workout plan
 */
export type createMealResponse201 = {
  data: CreateMeal201;
  status: 201;
};

export type createMealResponse401 = {
  data: CreateMeal401;
  status: 401;
};

export type createMealResponse404 = {
  data: CreateMeal404;
  status: 404;
};

export type createMealResponse500 = {
  data: CreateMeal500;
  status: 500;
};

export type createMealResponseSuccess = createMealResponse201 & {
  headers: Headers;
};
export type createMealResponseError = (
  | createMealResponse401
  | createMealResponse404
  | createMealResponse500
) & {
  headers: Headers;
};

export type createMealResponse =
  | createMealResponseSuccess
  | createMealResponseError;

export const getCreateMealUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}/meals`;
};

export const createMeal = async (
  workoutPlanId: string,
  createMealBody: CreateMealBody,
  options?: RequestInit,
): Promise<createMealResponse> => {
  return customFetch<createMealResponse>(getCreateMealUrl(workoutPlanId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMealBody),
  });
};

/**
 * @summary Update a meal
 */
export type updateMealResponse200 = {
  data: UpdateMeal200;
  status: 200;
};

export type updateMealResponse401 = {
  data: UpdateMeal401;
  status: 401;
};

export type updateMealResponse404 = {
  data: UpdateMeal404;
  status: 404;
};

export type updateMealResponse500 = {
  data: UpdateMeal500;
  status: 500;
};

export type updateMealResponseSuccess = updateMealResponse200 & {
  headers: Headers;
};
export type updateMealResponseError = (
  | updateMealResponse401
  | updateMealResponse404
  | updateMealResponse500
) & {
  headers: Headers;
};

export type updateMealResponse =
  | updateMealResponseSuccess
  | updateMealResponseError;

export const getUpdateMealUrl = (workoutPlanId: string, mealId: string) => {
  return `/workout-plans/${workoutPlanId}/meals/${mealId}`;
};

export const updateMeal = async (
  workoutPlanId: string,
  mealId: string,
  updateMealBody: UpdateMealBody,
  options?: RequestInit,
): Promise<updateMealResponse> => {
  return customFetch<updateMealResponse>(
    getUpdateMealUrl(workoutPlanId, mealId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateMealBody),
    },
  );
};

/**
 * @summary Delete a meal
 */
export type deleteMealResponse204 = {
  data: unknown;
  status: 204;
};

export type deleteMealResponse401 = {
  data: DeleteMeal401;
  status: 401;
};

export type deleteMealResponse404 = {
  data: DeleteMeal404;
  status: 404;
};

export type deleteMealResponse500 = {
  data: DeleteMeal500;
  status: 500;
};

export type deleteMealResponseSuccess = deleteMealResponse204 & {
  headers: Headers;
};
export type deleteMealResponseError = (
  | deleteMealResponse401
  | deleteMealResponse404
  | deleteMealResponse500
) & {
  headers: Headers;
};

export type deleteMealResponse =
  | deleteMealResponseSuccess
  | deleteMealResponseError;

export const getDeleteMealUrl = (workoutPlanId: string, mealId: string) => {
  return `/workout-plans/${workoutPlanId}/meals/${mealId}`;
};

export const deleteMeal = async (
  workoutPlanId: string,
  mealId: string,
  options?: RequestInit,
): Promise<deleteMealResponse> => {
  return customFetch<deleteMealResponse>(
    getDeleteMealUrl(workoutPlanId, mealId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Analyze a photo of a meal and estimate its foods and macros. The photo is not stored.
 */
export type analyzeMealPhotoResponse200 = {
  data: AnalyzeMealPhoto200;
  status: 200;
};

export type analyzeMealPhotoResponse401 = {
  data: AnalyzeMealPhoto401;
  status: 401;
};

export type analyzeMealPhotoResponse500 = {
  data: AnalyzeMealPhoto500;
  status: 500;
};

export type analyzeMealPhotoResponseSuccess = analyzeMealPhotoResponse200 & {
  headers: Headers;
};
export type analyzeMealPhotoResponseError = (
  | analyzeMealPhotoResponse401
  | analyzeMealPhotoResponse500
) & {
  headers: Headers;
};

export type analyzeMealPhotoResponse =
  | analyzeMealPhotoResponseSuccess
  | analyzeMealPhotoResponseError;

export const getAnalyzeMealPhotoUrl = () => {
  return `/meals/analyze-photo`;
};

export const analyzeMealPhoto = async (
  analyzeMealPhotoBody: AnalyzeMealPhotoBody,
  options?: RequestInit,
): Promise<analyzeMealPhotoResponse> => {
  return customFetch<analyzeMealPhotoResponse>(getAnalyzeMealPhotoUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(analyzeMealPhotoBody),
  });
};

/**
 * @summary List all workout plans with their completed sessions and stats
 */
export type getWorkoutSessionsResponse200 = {
  data: GetWorkoutSessions200Item[];
  status: 200;
};

export type getWorkoutSessionsResponse401 = {
  data: GetWorkoutSessions401;
  status: 401;
};

export type getWorkoutSessionsResponse500 = {
  data: GetWorkoutSessions500;
  status: 500;
};

export type getWorkoutSessionsResponseSuccess =
  getWorkoutSessionsResponse200 & {
    headers: Headers;
  };
export type getWorkoutSessionsResponseError = (
  | getWorkoutSessionsResponse401
  | getWorkoutSessionsResponse500
) & {
  headers: Headers;
};

export type getWorkoutSessionsResponse =
  | getWorkoutSessionsResponseSuccess
  | getWorkoutSessionsResponseError;

export const getGetWorkoutSessionsUrl = () => {
  return `/workout-sessions/`;
};

export const getWorkoutSessions = async (
  options?: RequestInit,
): Promise<getWorkoutSessionsResponse> => {
  return customFetch<getWorkoutSessionsResponse>(getGetWorkoutSessionsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Update an exercise's current load and log the change
 */
export type updateExerciseLoadResponse200 = {
  data: UpdateExerciseLoad200;
  status: 200;
};

export type updateExerciseLoadResponse401 = {
  data: UpdateExerciseLoad401;
  status: 401;
};

export type updateExerciseLoadResponse404 = {
  data: UpdateExerciseLoad404;
  status: 404;
};

export type updateExerciseLoadResponse500 = {
  data: UpdateExerciseLoad500;
  status: 500;
};

export type updateExerciseLoadResponseSuccess =
  updateExerciseLoadResponse200 & {
    headers: Headers;
  };
export type updateExerciseLoadResponseError = (
  | updateExerciseLoadResponse401
  | updateExerciseLoadResponse404
  | updateExerciseLoadResponse500
) & {
  headers: Headers;
};

export type updateExerciseLoadResponse =
  | updateExerciseLoadResponseSuccess
  | updateExerciseLoadResponseError;

export const getUpdateExerciseLoadUrl = (exerciseId: string) => {
  return `/exercises/${exerciseId}/load`;
};

export const updateExerciseLoad = async (
  exerciseId: string,
  updateExerciseLoadBody: UpdateExerciseLoadBody,
  options?: RequestInit,
): Promise<updateExerciseLoadResponse> => {
  return customFetch<updateExerciseLoadResponse>(
    getUpdateExerciseLoadUrl(exerciseId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateExerciseLoadBody),
    },
  );
};

/**
 * @summary List the load history for an exercise
 */
export type getExerciseLoadHistoryResponse200 = {
  data: GetExerciseLoadHistory200Item[];
  status: 200;
};

export type getExerciseLoadHistoryResponse401 = {
  data: GetExerciseLoadHistory401;
  status: 401;
};

export type getExerciseLoadHistoryResponse404 = {
  data: GetExerciseLoadHistory404;
  status: 404;
};

export type getExerciseLoadHistoryResponse500 = {
  data: GetExerciseLoadHistory500;
  status: 500;
};

export type getExerciseLoadHistoryResponseSuccess =
  getExerciseLoadHistoryResponse200 & {
    headers: Headers;
  };
export type getExerciseLoadHistoryResponseError = (
  | getExerciseLoadHistoryResponse401
  | getExerciseLoadHistoryResponse404
  | getExerciseLoadHistoryResponse500
) & {
  headers: Headers;
};

export type getExerciseLoadHistoryResponse =
  | getExerciseLoadHistoryResponseSuccess
  | getExerciseLoadHistoryResponseError;

export const getGetExerciseLoadHistoryUrl = (exerciseId: string) => {
  return `/exercises/${exerciseId}/load-history`;
};

export const getExerciseLoadHistory = async (
  exerciseId: string,
  options?: RequestInit,
): Promise<getExerciseLoadHistoryResponse> => {
  return customFetch<getExerciseLoadHistoryResponse>(
    getGetExerciseLoadHistoryUrl(exerciseId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get today's water intake entries, total, and daily goal
 */
export type getWaterIntakeTodayResponse200 = {
  data: GetWaterIntakeToday200;
  status: 200;
};

export type getWaterIntakeTodayResponse401 = {
  data: GetWaterIntakeToday401;
  status: 401;
};

export type getWaterIntakeTodayResponse500 = {
  data: GetWaterIntakeToday500;
  status: 500;
};

export type getWaterIntakeTodayResponseSuccess =
  getWaterIntakeTodayResponse200 & {
    headers: Headers;
  };
export type getWaterIntakeTodayResponseError = (
  | getWaterIntakeTodayResponse401
  | getWaterIntakeTodayResponse500
) & {
  headers: Headers;
};

export type getWaterIntakeTodayResponse =
  | getWaterIntakeTodayResponseSuccess
  | getWaterIntakeTodayResponseError;

export const getGetWaterIntakeTodayUrl = (
  params: GetWaterIntakeTodayParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/water-intake/?${stringifiedParams}`
    : `/water-intake/`;
};

export const getWaterIntakeToday = async (
  params: GetWaterIntakeTodayParams,
  options?: RequestInit,
): Promise<getWaterIntakeTodayResponse> => {
  return customFetch<getWaterIntakeTodayResponse>(
    getGetWaterIntakeTodayUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Log a water intake entry
 */
export type createWaterIntakeEntryResponse201 = {
  data: CreateWaterIntakeEntry201;
  status: 201;
};

export type createWaterIntakeEntryResponse401 = {
  data: CreateWaterIntakeEntry401;
  status: 401;
};

export type createWaterIntakeEntryResponse500 = {
  data: CreateWaterIntakeEntry500;
  status: 500;
};

export type createWaterIntakeEntryResponseSuccess =
  createWaterIntakeEntryResponse201 & {
    headers: Headers;
  };
export type createWaterIntakeEntryResponseError = (
  | createWaterIntakeEntryResponse401
  | createWaterIntakeEntryResponse500
) & {
  headers: Headers;
};

export type createWaterIntakeEntryResponse =
  | createWaterIntakeEntryResponseSuccess
  | createWaterIntakeEntryResponseError;

export const getCreateWaterIntakeEntryUrl = () => {
  return `/water-intake/`;
};

export const createWaterIntakeEntry = async (
  createWaterIntakeEntryBody: CreateWaterIntakeEntryBody,
  options?: RequestInit,
): Promise<createWaterIntakeEntryResponse> => {
  return customFetch<createWaterIntakeEntryResponse>(
    getCreateWaterIntakeEntryUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createWaterIntakeEntryBody),
    },
  );
};

/**
 * @summary List muscle groups with their exercise templates
 */
export type listMuscleGroupsResponse200 = {
  data: ListMuscleGroups200Item[];
  status: 200;
};

export type listMuscleGroupsResponse401 = {
  data: ListMuscleGroups401;
  status: 401;
};

export type listMuscleGroupsResponse500 = {
  data: ListMuscleGroups500;
  status: 500;
};

export type listMuscleGroupsResponseSuccess = listMuscleGroupsResponse200 & {
  headers: Headers;
};
export type listMuscleGroupsResponseError = (
  | listMuscleGroupsResponse401
  | listMuscleGroupsResponse500
) & {
  headers: Headers;
};

export type listMuscleGroupsResponse =
  | listMuscleGroupsResponseSuccess
  | listMuscleGroupsResponseError;

export const getListMuscleGroupsUrl = () => {
  return `/muscle-groups/`;
};

export const listMuscleGroups = async (
  options?: RequestInit,
): Promise<listMuscleGroupsResponse> => {
  return customFetch<listMuscleGroupsResponse>(getListMuscleGroupsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a muscle group
 */
export type createMuscleGroupResponse201 = {
  data: CreateMuscleGroup201;
  status: 201;
};

export type createMuscleGroupResponse401 = {
  data: CreateMuscleGroup401;
  status: 401;
};

export type createMuscleGroupResponse409 = {
  data: CreateMuscleGroup409;
  status: 409;
};

export type createMuscleGroupResponse500 = {
  data: CreateMuscleGroup500;
  status: 500;
};

export type createMuscleGroupResponseSuccess = createMuscleGroupResponse201 & {
  headers: Headers;
};
export type createMuscleGroupResponseError = (
  | createMuscleGroupResponse401
  | createMuscleGroupResponse409
  | createMuscleGroupResponse500
) & {
  headers: Headers;
};

export type createMuscleGroupResponse =
  | createMuscleGroupResponseSuccess
  | createMuscleGroupResponseError;

export const getCreateMuscleGroupUrl = () => {
  return `/muscle-groups/`;
};

export const createMuscleGroup = async (
  createMuscleGroupBody: CreateMuscleGroupBody,
  options?: RequestInit,
): Promise<createMuscleGroupResponse> => {
  return customFetch<createMuscleGroupResponse>(getCreateMuscleGroupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMuscleGroupBody),
  });
};

/**
 * @summary Update a muscle group
 */
export type updateMuscleGroupResponse200 = {
  data: UpdateMuscleGroup200;
  status: 200;
};

export type updateMuscleGroupResponse401 = {
  data: UpdateMuscleGroup401;
  status: 401;
};

export type updateMuscleGroupResponse404 = {
  data: UpdateMuscleGroup404;
  status: 404;
};

export type updateMuscleGroupResponse409 = {
  data: UpdateMuscleGroup409;
  status: 409;
};

export type updateMuscleGroupResponse500 = {
  data: UpdateMuscleGroup500;
  status: 500;
};

export type updateMuscleGroupResponseSuccess = updateMuscleGroupResponse200 & {
  headers: Headers;
};
export type updateMuscleGroupResponseError = (
  | updateMuscleGroupResponse401
  | updateMuscleGroupResponse404
  | updateMuscleGroupResponse409
  | updateMuscleGroupResponse500
) & {
  headers: Headers;
};

export type updateMuscleGroupResponse =
  | updateMuscleGroupResponseSuccess
  | updateMuscleGroupResponseError;

export const getUpdateMuscleGroupUrl = (muscleGroupId: string) => {
  return `/muscle-groups/${muscleGroupId}`;
};

export const updateMuscleGroup = async (
  muscleGroupId: string,
  updateMuscleGroupBody: UpdateMuscleGroupBody,
  options?: RequestInit,
): Promise<updateMuscleGroupResponse> => {
  return customFetch<updateMuscleGroupResponse>(
    getUpdateMuscleGroupUrl(muscleGroupId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateMuscleGroupBody),
    },
  );
};

/**
 * @summary Delete a muscle group
 */
export type deleteMuscleGroupResponse204 = {
  data: unknown;
  status: 204;
};

export type deleteMuscleGroupResponse401 = {
  data: DeleteMuscleGroup401;
  status: 401;
};

export type deleteMuscleGroupResponse404 = {
  data: DeleteMuscleGroup404;
  status: 404;
};

export type deleteMuscleGroupResponse500 = {
  data: DeleteMuscleGroup500;
  status: 500;
};

export type deleteMuscleGroupResponseSuccess = deleteMuscleGroupResponse204 & {
  headers: Headers;
};
export type deleteMuscleGroupResponseError = (
  | deleteMuscleGroupResponse401
  | deleteMuscleGroupResponse404
  | deleteMuscleGroupResponse500
) & {
  headers: Headers;
};

export type deleteMuscleGroupResponse =
  | deleteMuscleGroupResponseSuccess
  | deleteMuscleGroupResponseError;

export const getDeleteMuscleGroupUrl = (muscleGroupId: string) => {
  return `/muscle-groups/${muscleGroupId}`;
};

export const deleteMuscleGroup = async (
  muscleGroupId: string,
  options?: RequestInit,
): Promise<deleteMuscleGroupResponse> => {
  return customFetch<deleteMuscleGroupResponse>(
    getDeleteMuscleGroupUrl(muscleGroupId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Create an exercise template within a muscle group
 */
export type createExerciseTemplateResponse201 = {
  data: CreateExerciseTemplate201;
  status: 201;
};

export type createExerciseTemplateResponse401 = {
  data: CreateExerciseTemplate401;
  status: 401;
};

export type createExerciseTemplateResponse404 = {
  data: CreateExerciseTemplate404;
  status: 404;
};

export type createExerciseTemplateResponse409 = {
  data: CreateExerciseTemplate409;
  status: 409;
};

export type createExerciseTemplateResponse500 = {
  data: CreateExerciseTemplate500;
  status: 500;
};

export type createExerciseTemplateResponseSuccess =
  createExerciseTemplateResponse201 & {
    headers: Headers;
  };
export type createExerciseTemplateResponseError = (
  | createExerciseTemplateResponse401
  | createExerciseTemplateResponse404
  | createExerciseTemplateResponse409
  | createExerciseTemplateResponse500
) & {
  headers: Headers;
};

export type createExerciseTemplateResponse =
  | createExerciseTemplateResponseSuccess
  | createExerciseTemplateResponseError;

export const getCreateExerciseTemplateUrl = (muscleGroupId: string) => {
  return `/muscle-groups/${muscleGroupId}/exercise-templates`;
};

export const createExerciseTemplate = async (
  muscleGroupId: string,
  createExerciseTemplateBody: CreateExerciseTemplateBody,
  options?: RequestInit,
): Promise<createExerciseTemplateResponse> => {
  return customFetch<createExerciseTemplateResponse>(
    getCreateExerciseTemplateUrl(muscleGroupId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createExerciseTemplateBody),
    },
  );
};

/**
 * @summary Update an exercise template
 */
export type updateExerciseTemplateResponse200 = {
  data: UpdateExerciseTemplate200;
  status: 200;
};

export type updateExerciseTemplateResponse401 = {
  data: UpdateExerciseTemplate401;
  status: 401;
};

export type updateExerciseTemplateResponse404 = {
  data: UpdateExerciseTemplate404;
  status: 404;
};

export type updateExerciseTemplateResponse409 = {
  data: UpdateExerciseTemplate409;
  status: 409;
};

export type updateExerciseTemplateResponse500 = {
  data: UpdateExerciseTemplate500;
  status: 500;
};

export type updateExerciseTemplateResponseSuccess =
  updateExerciseTemplateResponse200 & {
    headers: Headers;
  };
export type updateExerciseTemplateResponseError = (
  | updateExerciseTemplateResponse401
  | updateExerciseTemplateResponse404
  | updateExerciseTemplateResponse409
  | updateExerciseTemplateResponse500
) & {
  headers: Headers;
};

export type updateExerciseTemplateResponse =
  | updateExerciseTemplateResponseSuccess
  | updateExerciseTemplateResponseError;

export const getUpdateExerciseTemplateUrl = (
  muscleGroupId: string,
  exerciseTemplateId: string,
) => {
  return `/muscle-groups/${muscleGroupId}/exercise-templates/${exerciseTemplateId}`;
};

export const updateExerciseTemplate = async (
  muscleGroupId: string,
  exerciseTemplateId: string,
  updateExerciseTemplateBody: UpdateExerciseTemplateBody,
  options?: RequestInit,
): Promise<updateExerciseTemplateResponse> => {
  return customFetch<updateExerciseTemplateResponse>(
    getUpdateExerciseTemplateUrl(muscleGroupId, exerciseTemplateId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateExerciseTemplateBody),
    },
  );
};

/**
 * @summary Delete an exercise template
 */
export type deleteExerciseTemplateResponse204 = {
  data: unknown;
  status: 204;
};

export type deleteExerciseTemplateResponse401 = {
  data: DeleteExerciseTemplate401;
  status: 401;
};

export type deleteExerciseTemplateResponse404 = {
  data: DeleteExerciseTemplate404;
  status: 404;
};

export type deleteExerciseTemplateResponse500 = {
  data: DeleteExerciseTemplate500;
  status: 500;
};

export type deleteExerciseTemplateResponseSuccess =
  deleteExerciseTemplateResponse204 & {
    headers: Headers;
  };
export type deleteExerciseTemplateResponseError = (
  | deleteExerciseTemplateResponse401
  | deleteExerciseTemplateResponse404
  | deleteExerciseTemplateResponse500
) & {
  headers: Headers;
};

export type deleteExerciseTemplateResponse =
  | deleteExerciseTemplateResponseSuccess
  | deleteExerciseTemplateResponseError;

export const getDeleteExerciseTemplateUrl = (
  muscleGroupId: string,
  exerciseTemplateId: string,
) => {
  return `/muscle-groups/${muscleGroupId}/exercise-templates/${exerciseTemplateId}`;
};

export const deleteExerciseTemplate = async (
  muscleGroupId: string,
  exerciseTemplateId: string,
  options?: RequestInit,
): Promise<deleteExerciseTemplateResponse> => {
  return customFetch<deleteExerciseTemplateResponse>(
    getDeleteExerciseTemplateUrl(muscleGroupId, exerciseTemplateId),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};

/**
 * Hello world
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
